### ISSUE TITLE
problem with roslaunch

### ISSUE THREAD

**Issue by klauswq** [surgical-vision/youbot_stack#1]
The error occurred when i executed the command : roslaunch youbot_simulator youbot_sim.launch gui:=true . The error was as follows:

WARNING: cannot create log directory [/home/qi/.ros/log/23ba9c44-adfa-11e7-bcd2-000c29d08503]. Please set ROS_LOG_DIR to a writable location.
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: Traditional processing is deprecated. Switch to --inorder processing!
To check for compatibility of your document, use option --check-order.
For more infos, see http://wiki.ros.org/xacro#Processing_Order
inconsistent namespace redefinitions for xmlns:xacro:
 old: http://playerstage.sourceforge.net/gazebo/xmlschema/#interface
 new: http://ros.org/wiki/xacro (/home/qi/catkin_ws/src/youbot_stack/youbot_description/urdf/youbot_arm/arm.urdf.xacro)
inconsistent namespace redefinitions for xmlns:xacro:
 old: http://playerstage.sourceforge.net/gazebo/xmlschema/#interface
 new: http://ros.org/wiki/xacro (/home/qi/catkin_ws/src/youbot_stack/youbot_description/urdf/youbot_gripper/gripper.urdf.xacro)
deprecated: xacro tags should be prepended with 'xacro' xml namespace.
Use the following script to fix incorrect usage:
        find . -iname "*.xacro" | xargs sed -i 's#<\([/]\?\)\(if\|unless\|include\|arg\|property\|macro\|insert_block\)#<\1xacro:\2#g'
when processing file: /home/qi/catkin_ws/src/youbot_stack/youbot_description/robots/youbot_arm_only.urdf.xacro

xacro.py is deprecated; please use xacro instead
started roslaunch server http://qi-virtual-machine:43761/

SUMMARY
========

PARAMETERS
 * /EffortJointInterface_J1_controller/joint: arm_joint_1
 * /EffortJointInterface_J1_controller/pid/d: 10.0
 * /EffortJointInterface_J1_controller/pid/i: 0.01
 * /EffortJointInterface_J1_controller/pid/p: 100.0
 * /EffortJointInterface_J1_controller/type: effort_controller...
 * /EffortJointInterface_J2_controller/joint: arm_joint_2
 * /EffortJointInterface_J2_controller/pid/d: 10.0
 * /EffortJointInterface_J2_controller/pid/i: 0.01
 * /EffortJointInterface_J2_controller/pid/p: 100.0
 * /EffortJointInterface_J2_controller/type: effort_controller...
 * /EffortJointInterface_J3_controller/joint: arm_joint_3
 * /EffortJointInterface_J3_controller/pid/d: 10.0
 * /EffortJointInterface_J3_controller/pid/i: 0.01
 * /EffortJointInterface_J3_controller/pid/p: 100.0
 * /EffortJointInterface_J3_controller/type: effort_controller...
 * /EffortJointInterface_J4_controller/joint: arm_joint_4
 * /EffortJointInterface_J4_controller/pid/d: 10.0
 * /EffortJointInterface_J4_controller/pid/i: 0.01
 * /EffortJointInterface_J4_controller/pid/p: 100.0
 * /EffortJointInterface_J4_controller/type: effort_controller...
 * /EffortJointInterface_J5_controller/joint: arm_joint_5
 * /EffortJointInterface_J5_controller/pid/d: 10.0
 * /EffortJointInterface_J5_controller/pid/i: 0.01
 * /EffortJointInterface_J5_controller/pid/p: 100.0
 * /EffortJointInterface_J5_controller/type: effort_controller...
 * /EffortJointInterface_trajectory_controller/action_monitor_rate: 30
 * /EffortJointInterface_trajectory_controller/constraints/goal_time: 0.5
 * /EffortJointInterface_trajectory_controller/gains/arm_joint_1/d: 30
 * /EffortJointInterface_trajectory_controller/gains/arm_joint_1/i: 15
 * /EffortJointInterface_trajectory_controller/gains/arm_joint_1/i_clamp: 30
 * /EffortJointInterface_trajectory_controller/gains/arm_joint_1/p: 500
 * /EffortJointInterface_trajectory_controller/gains/arm_joint_2/d: 10
 * /EffortJointInterface_trajectory_controller/gains/arm_joint_2/i: 10
 * /EffortJointInterface_trajectory_controller/gains/arm_joint_2/i_clamp: 30
 * /EffortJointInterface_trajectory_controller/gains/arm_joint_2/p: 200
 * /EffortJointInterface_trajectory_controller/gains/arm_joint_3/d: 10
 * /EffortJointInterface_trajectory_controller/gains/arm_joint_3/i: 15
 * /EffortJointInterface_trajectory_controller/gains/arm_joint_3/i_clamp: 30
 * /EffortJointInterface_trajectory_controller/gains/arm_joint_3/p: 65
 * /EffortJointInterface_trajectory_controller/gains/arm_joint_4/d: 7
 * /EffortJointInterface_trajectory_controller/gains/arm_joint_4/i: 12
 * /EffortJointInterface_trajectory_controller/gains/arm_joint_4/i_clamp: 30
 * /EffortJointInterface_trajectory_controller/gains/arm_joint_4/p: 31
 * /EffortJointInterface_trajectory_controller/gains/arm_joint_5/d: 3
 * /EffortJointInterface_trajectory_controller/gains/arm_joint_5/i: 5
 * /EffortJointInterface_trajectory_controller/gains/arm_joint_5/i_clamp: 30
 * /EffortJointInterface_trajectory_controller/gains/arm_joint_5/p: 23
 * /EffortJointInterface_trajectory_controller/joints: ['arm_joint_1', '...
 * /EffortJointInterface_trajectory_controller/state_publish_rate: 25
 * /EffortJointInterface_trajectory_controller/stop_trajectory_duration: 0
 * /EffortJointInterface_trajectory_controller/type: effort_controller...
 * /PositionJointInterface_J1_controller/joint: arm_joint_1
 * /PositionJointInterface_J1_controller/type: position_controll...
 * /PositionJointInterface_J2_controller/joint: arm_joint_2
 * /PositionJointInterface_J2_controller/type: position_controll...
 * /PositionJointInterface_J3_controller/joint: arm_joint_3
 * /PositionJointInterface_J3_controller/type: position_controll...
 * /PositionJointInterface_J4_controller/joint: arm_joint_4
 * /PositionJointInterface_J4_controller/type: position_controll...
 * /PositionJointInterface_J5_controller/joint: arm_joint_5
 * /PositionJointInterface_J5_controller/type: position_controll...
 * /PositionJointInterface_trajectory_controller/action_monitor_rate: 200
 * /PositionJointInterface_trajectory_controller/constraints/goal_time: 0.5
 * /PositionJointInterface_trajectory_controller/joints: ['arm_joint_1', '...
 * /PositionJointInterface_trajectory_controller/state_publish_rate: 200
 * /PositionJointInterface_trajectory_controller/stop_trajectory_duration: 0
 * /PositionJointInterface_trajectory_controller/type: position_controll...
 * /joint_state_controller/publish_rate: 200
 * /joint_state_controller/type: joint_state_contr...
 * /robot_description: <?xml version="1....
 * /rosdistro: kinetic
 * /rosversion: 1.12.7
 * /use_sim_time: True

NODES
  /
    controller_spawner (controller_manager/spawner)
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    youbot_load_gazebo_model (gazebo_ros/spawn_model)

auto-starting new master
No handlers could be found for logger "roslaunch"
[master] ERROR: unable to configure logging [unable to create directory for log file [/home/qi/.ros/log/23ba9c44-adfa-11e7-bcd2-000c29d08503].
Please check permissions.]
process[master]: started with pid [21669]
[master] process has died [pid 21669, exit code 1, cmd rosmaster --core -p 11311 -w 3].
ERROR: could not contact master [http://localhost:11311]
The traceback for the exception was written to the log file
[master] killing on exit

**Comment by grdwyer** [comment]
Can you try `roswtf`?
Do you have a logging directory? It should be /home/qi/.ros/log

**Comment by grdwyer** [comment]
I'm going to assume you've fixed this and close the issue.
