### ISSUE TITLE
Catkin_make Failed

### ISSUE THREAD

**Issue by ossieG** [surgical-vision/youbot_stack#2]
I have cloned to src and updated and tried catkin_make but it failed.
Should I a branch at a time?
Below is the error that I got:
-----------------------------------------------------------------------------------------------------------------
[ 97%] Linking CXX shared library /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/lib/libYouBotDriver.so
[ 97%] Built target YouBotDriver
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed
osanda@MyPC101:~/catkin_ws$ hist
-------------------------------------------------------------------------------------------------------------------

This is the history of commands leading to that:
--------------------------------------------------------------------------------------------------------------------
 1  sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
    2  sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
    3  ls
    4  cd /
    5  ls
    6  cd home/
    7  ls
    8  cd
    9  sudo apt-get update
  ` 10  sudo apt-get install ros-kinetic-desktop-full
   11  df
   12  df -h
   13  sudo rosdep init
   14  rosdep update
   15  echo "source /opt/ros/kinetic/setup.bash" >> ~/.bashrc
   16  source ~/.bashrc
   17  sudo apt-get install python-rosinstall python-rosinstall-generator python-wstool build-essential
   18  printenv | grep ROS
   19  mkdir -p ~/catkin_ws/src
   20  cd ~/catkin_ws/
   21  catkin_make
   22  source devel/setup.bash
   23  echo $ROS_PACKAGE_PATH
   24  sudo apt install ros-kinetic-controller-manager ros-kinetic-joint-state-controller ros-kinetic-effort-controllers ros-kinetic-gazebo-ros-control
   25  ls
   26  cd src/
   27  ls
   28  git clone https://github.com/surgical-vision/youbot_stack.git youbot_stack
   29  ls
   30  cd youbot_stack/
   31  ls
   32  git submodule update --init
   33  cd ..
   34  catkin_make
   35  history
--------------------------------------------------------------------------------------------------------------

**Comment by grdwyer** [comment]
Can you post the output from catkin_make? There's generally an error tag a bit further up in the output.

**Comment by ossieG** [comment]
The following is what I get without recloning:
-------------------------------------------------------------------------------------------
osanda@MyPC101:~/catkin_ws$ catkin_make
Base path: /home/osanda/catkin_ws
Source space: /home/osanda/catkin_ws/src
Build space: /home/osanda/catkin_ws/build
Devel space: /home/osanda/catkin_ws/devel
Install space: /home/osanda/catkin_ws/install
####
#### Running command: "make cmake_check_build_system" in "/home/osanda/catkin_ws/build"
####
####
#### Running command: "make -j4 -l4" in "/home/osanda/catkin_ws/build"
####
[  4%] Built target displayIpAddress
[ 29%] Built target soem
[ 34%] Built target youbot_joint_pub
[ 36%] Linking CXX executable /home/osanda/catkin_ws/devel/lib/youbot_joint_control/youbot_joint_control
[ 95%] Built target YouBotDriver
Scanning dependencies of target YouBotDriverShared
make[2]: Circular /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/lib/libYouBotDriver.so <- /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/lib/libYouBotDriver.so dependency dropped.
[ 97%] Built target YouBotDriverShared
/usr/bin/ld: warning: libsoem.so, needed by /home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so, not found (try using -rpath or -rpath-link)
/home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_iserror'
/home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_init'
/home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_mbxsend'
/home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_readstate'
/home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_ALstatuscode2string'
/home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_mbxreceive'
/home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_send_processdata'
/home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_statecheck'
/home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_receive_processdata'
/home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_slavecount'
/home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_slave'
/home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_close'
/home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_writestate'
/home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_config'
collect2: error: ld returned 1 exit status
youbot_stack/youbot_joint_control/CMakeFiles/youbot_joint_control.dir/build.make:114: recipe for target '/home/osanda/catkin_ws/devel/lib/youbot_joint_control/youbot_joint_control' failed
make[2]: *** [/home/osanda/catkin_ws/devel/lib/youbot_joint_control/youbot_joint_control] Error 1
CMakeFiles/Makefile2:1578: recipe for target 'youbot_stack/youbot_joint_control/CMakeFiles/youbot_joint_control.dir/all' failed
make[1]: *** [youbot_stack/youbot_joint_control/CMakeFiles/youbot_joint_control.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed
-----------------------------------------------------------------------------------------------------------------

**Comment by ossieG** [comment]
And this is after deleting youbot_stack and recloning:
---------------------------------------------------------------------------------

> osanda@MyPC101:~/catkin_ws$ catkin_make
> Base path: /home/osanda/catkin_ws
> Source space: /home/osanda/catkin_ws/src
> Build space: /home/osanda/catkin_ws/build
> Devel space: /home/osanda/catkin_ws/devel
> Install space: /home/osanda/catkin_ws/install
> ####
> #### Running command: "make cmake_check_build_system" in "/home/osanda/catkin_ws/build"
> ####
> -- Using CATKIN_DEVEL_PREFIX: /home/osanda/catkin_ws/devel
> -- Using CMAKE_PREFIX_PATH: /opt/ros/kinetic
> -- This workspace overlays: /opt/ros/kinetic
> -- Using PYTHON_EXECUTABLE: /usr/bin/python
> -- Using Debian Python package layout
> -- Using empy: /usr/bin/empy
> -- Using CATKIN_ENABLE_TESTING: ON
> -- Call enable_testing()
> -- Using CATKIN_TEST_RESULTS_DIR: /home/osanda/catkin_ws/build/test_results
> -- Found gtest sources under '/usr/src/gtest': gtests will be built
> -- Using Python nosetests: /usr/bin/nosetests-2.7
> -- catkin 0.7.6
> -- BUILD_SHARED_LIBS is on
> -- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> -- ~~  traversing 6 packages in topological order:
> -- ~~  - youbot_description
> -- ~~  - youbot_driver
> -- ~~  - youbot_joint_control
> -- ~~  - youbot_joint_pub
> -- ~~  - youbot_joint_pub_py
> -- ~~  - youbot_simulator
> -- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> -- +++ processing catkin package: 'youbot_description'
> -- ==> add_subdirectory(youbot_stack/youbot_description)
> -- +++ processing catkin package: 'youbot_driver'
> -- ==> add_subdirectory(youbot_stack/youbot_driver)
> -- Boost version: 1.58.0
> -- Found the following Boost libraries:
> --   thread
> --   date_time
> --   filesystem
> --   system
> --   regex
> --   chrono
> --   atomic
> -- SUCCESSFUL: Boost found
> -- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
> -- Ensure you cppunit installed version is at least
> 1.12.0
> CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:166 (message):
>   catkin_package() DEPENDS on 'boost-all' but neither
>   'boost-all_INCLUDE_DIRS' nor 'boost-all_LIBRARIES' is defined.
> Call Stack (most recent call first):
>   /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
>   youbot_stack/youbot_driver/CMakeLists.txt:205 (catkin_package)
> 
> 
> -- +++ processing catkin package: 'youbot_joint_control'
> -- ==> add_subdirectory(youbot_stack/youbot_joint_control)
> -- +++ processing catkin package: 'youbot_joint_pub'
> -- ==> add_subdirectory(youbot_stack/youbot_joint_pub)
> -- +++ processing catkin package: 'youbot_joint_pub_py'
> -- ==> add_subdirectory(youbot_stack/youbot_joint_pub_py)
> -- +++ processing catkin package: 'youbot_simulator'
> -- ==> add_subdirectory(youbot_stack/youbot_simulator)
> -- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/osanda/catkin_ws/build
> ####
> #### Running command: "make -j4 -l4" in "/home/osanda/catkin_ws/build"
> ####
> Scanning dependencies of target displayIpAddress
> Scanning dependencies of target youbot_joint_pub
> Scanning dependencies of target soem
> Scanning dependencies of target youbot_joint_control
> [  2%] Building CXX object youbot_stack/youbot_driver/display/CMakeFiles/displayIpAddress.dir/DisplayIpAddress.cpp.o
> [  4%] Building C object youbot_stack/youbot_driver/soem/CMakeFiles/soem.dir/src/ethercatbase.c.o
> [  7%] Building CXX object youbot_stack/youbot_joint_pub/CMakeFiles/youbot_joint_pub.dir/src/main.cpp.o
> [  9%] Building CXX object youbot_stack/youbot_joint_control/CMakeFiles/youbot_joint_control.dir/src/main.cpp.o
> [ 12%] Building C object youbot_stack/youbot_driver/soem/CMakeFiles/soem.dir/src/ethercatcoe.c.o
> [ 14%] Building C object youbot_stack/youbot_driver/soem/CMakeFiles/soem.dir/src/ethercatconfig.c.o
> /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/soem/src/ethercatconfig.c: In function ‘ec_config_init’:
> /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/soem/src/ethercatconfig.c:141:62: warning: variable ‘mbx_rl’ set but not used [-Wunused-but-set-variable]
>      uint16 w, slave, ADPh, configadr, mbx_wo, mbx_ro, mbx_l, mbx_rl, ssigen;
>                                                               ^
> /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/soem/src/ethercatconfig.c:141:55: warning: variable ‘mbx_l’ set but not used [-Wunused-but-set-variable]
>      uint16 w, slave, ADPh, configadr, mbx_wo, mbx_ro, mbx_l, mbx_rl, ssigen;
>                                                        ^
> /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/soem/src/ethercatconfig.c:141:47: warning: variable ‘mbx_ro’ set but not used [-Wunused-but-set-variable]
>      uint16 w, slave, ADPh, configadr, mbx_wo, mbx_ro, mbx_l, mbx_rl, ssigen;
>                                                ^
> /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/soem/src/ethercatconfig.c:141:39: warning: variable ‘mbx_wo’ set but not used [-Wunused-but-set-variable]
>      uint16 w, slave, ADPh, configadr, mbx_wo, mbx_ro, mbx_l, mbx_rl, ssigen;
>                                        ^
> /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/soem/src/ethercatconfig.c: In function ‘ec_config_map_group’:
> /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/soem/src/ethercatconfig.c:484:11: warning: variable ‘rval’ set but not used [-Wunused-but-set-variable]
>   int nSM, rval;
>            ^
> [ 17%] Linking CXX executable /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/bin/displayIpAddress
> [ 19%] Building C object youbot_stack/youbot_driver/soem/CMakeFiles/soem.dir/src/ethercatfoe.c.o
> [ 21%] Building C object youbot_stack/youbot_driver/soem/CMakeFiles/soem.dir/src/ethercatsoe.c.o
> [ 21%] Built target displayIpAddress
> [ 24%] Building C object youbot_stack/youbot_driver/soem/CMakeFiles/soem.dir/src/ethercatmain.c.o
> [ 26%] Building C object youbot_stack/youbot_driver/soem/CMakeFiles/soem.dir/src/ethercatprint.c.o
> /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/soem/src/ethercatmain.c: In function ‘ec_siistring’:
> /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/soem/src/ethercatmain.c:376:25: warning: variable ‘p’ set but not used [-Wunused-but-set-variable]
>      uint16 a,i,j,l,n,ba,p;
>                          ^
> /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/soem/src/ethercatmain.c: In function ‘ec_siiSM’:
> /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/soem/src/ethercatmain.c:452:16: warning: variable ‘l’ set but not used [-Wunused-but-set-variable]
>      uint16 a,w,l;
>                 ^
> [ 29%] Building C object youbot_stack/youbot_driver/soem/CMakeFiles/soem.dir/src/nicdrv.c.o
> /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/soem/src/nicdrv.c: In function ‘ec_setupnic’:
> /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/soem/src/nicdrv.c:192:24: warning: variable ‘fl’ set but not used [-Wunused-but-set-variable]
>   int r, rval, ifindex, fl;
>                         ^
> [ 31%] Building C object youbot_stack/youbot_driver/soem/CMakeFiles/soem.dir/src/ethercatdc.c.o
> /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/soem/src/ethercatdc.c: In function ‘ec_dcsync0’:
> /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/soem/src/ethercatdc.c:71:12: warning: variable ‘wc’ set but not used [-Wunused-but-set-variable]
>      uint16 wc, slaveh;
>             ^
> /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/soem/src/ethercatdc.c: In function ‘ec_dcsync01’:
> /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/soem/src/ethercatdc.c:123:12: warning: variable ‘wc’ set but not used [-Wunused-but-set-variable]
>      uint16 wc, slaveh;
>             ^
> /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/soem/src/ethercatdc.c: In function ‘ec_configdc’:
> /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/soem/src/ethercatdc.c:268:15: warning: variable ‘wc’ set but not used [-Wunused-but-set-variable]
>      uint16 i, wc, slaveh, parent, child;
>                ^
> [ 34%] Linking C shared library /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/lib/libsoem.so
> [ 34%] Built target soem
> Scanning dependencies of target YouBotDriver
> [ 39%] Building CXX object youbot_stack/youbot_driver/CMakeFiles/YouBotDriver.dir/youbot/EthercatMaster.cpp.o
> [ 39%] Building CXX object youbot_stack/youbot_driver/CMakeFiles/YouBotDriver.dir/youbot/EthercatMasterWithThread.cpp.o
> [ 41%] Linking CXX executable /home/osanda/catkin_ws/devel/lib/youbot_joint_pub/youbot_joint_pub
> [ 41%] Built target youbot_joint_pub
> [ 43%] Building CXX object youbot_stack/youbot_driver/CMakeFiles/YouBotDriver.dir/youbot/EthercatMasterWithoutThread.cpp.o
> /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/youbot/EthercatMasterWithThread.cpp: In member function ‘void youbot::EthercatMasterWithThread::updateSensorActorValues()’:
> /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/youbot/EthercatMasterWithThread.cpp:567:38: warning: variable ‘timeSum’ set but not used [-Wunused-but-set-variable]
>      boost::posix_time::time_duration timeSum = startTime - startTime;
>                                       ^
> [ 46%] Building CXX object youbot_stack/youbot_driver/CMakeFiles/YouBotDriver.dir/generic/Logger.cpp.o
> [ 48%] Linking CXX executable /home/osanda/catkin_ws/devel/lib/youbot_joint_control/youbot_joint_control
> /usr/bin/ld: warning: libsoem.so, needed by /home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so, not found (try using -rpath or -rpath-link)
> /home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_iserror'
> /home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_init'
> /home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_mbxsend'
> /home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_readstate'
> /home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_ALstatuscode2string'
> /home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_mbxreceive'
> /home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_send_processdata'
> /home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_statecheck'
> /home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_receive_processdata'
> /home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_slavecount'
> /home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_slave'
> /home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_close'
> /home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_writestate'
> /home/osanda/catkin_ws/src/youbot_stack/youbot_joint_control/lib/libYouBotDriver.so: undefined reference to `ec_config'
> collect2: error: ld returned 1 exit status
> youbot_stack/youbot_joint_control/CMakeFiles/youbot_joint_control.dir/build.make:114: recipe for target '/home/osanda/catkin_ws/devel/lib/youbot_joint_control/youbot_joint_control' failed
> make[2]: *** [/home/osanda/catkin_ws/devel/lib/youbot_joint_control/youbot_joint_control] Error 1
> CMakeFiles/Makefile2:1578: recipe for target 'youbot_stack/youbot_joint_control/CMakeFiles/youbot_joint_control.dir/all' failed
> make[1]: *** [youbot_stack/youbot_joint_control/CMakeFiles/youbot_joint_control.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [ 51%] Building CXX object youbot_stack/youbot_driver/CMakeFiles/YouBotDriver.dir/generic/ConfigFile.cpp.o
> [ 53%] Building CXX object youbot_stack/youbot_driver/CMakeFiles/YouBotDriver.dir/generic/PidController.cpp.o
> [ 56%] Building CXX object youbot_stack/youbot_driver/CMakeFiles/YouBotDriver.dir/generic-joint/JointData.cpp.o
> [ 58%] Building CXX object youbot_stack/youbot_driver/CMakeFiles/YouBotDriver.dir/generic-joint/JointTrajectory.cpp.o
> [ 60%] Building CXX object youbot_stack/youbot_driver/CMakeFiles/YouBotDriver.dir/youbot/YouBotJoint.cpp.o
> [ 63%] Building CXX object youbot_stack/youbot_driver/CMakeFiles/YouBotDriver.dir/youbot/JointLimitMonitor.cpp.o
> [ 65%] Building CXX object youbot_stack/youbot_driver/CMakeFiles/YouBotDriver.dir/youbot/YouBotBase.cpp.o
> [ 68%] Building CXX object youbot_stack/youbot_driver/CMakeFiles/YouBotDriver.dir/youbot/YouBotManipulator.cpp.o
> [ 70%] Building CXX object youbot_stack/youbot_driver/CMakeFiles/YouBotDriver.dir/youbot/YouBotGripper.cpp.o
> [ 73%] Building CXX object youbot_stack/youbot_driver/CMakeFiles/YouBotDriver.dir/youbot/YouBotGripperBar.cpp.o
> [ 75%] Building CXX object youbot_stack/youbot_driver/CMakeFiles/YouBotDriver.dir/youbot/YouBotGripperParameter.cpp.o
> [ 78%] Building CXX object youbot_stack/youbot_driver/CMakeFiles/YouBotDriver.dir/youbot/DataTrace.cpp.o
> [ 80%] Building CXX object youbot_stack/youbot_driver/CMakeFiles/YouBotDriver.dir/youbot/GripperDataTrace.cpp.o
> [ 82%] Building CXX object youbot_stack/youbot_driver/CMakeFiles/YouBotDriver.dir/youbot/YouBotJointParameter.cpp.o
> [ 85%] Building CXX object youbot_stack/youbot_driver/CMakeFiles/YouBotDriver.dir/youbot/YouBotJointParameterReadOnly.cpp.o
> [ 87%] Building CXX object youbot_stack/youbot_driver/CMakeFiles/YouBotDriver.dir/youbot/YouBotJointParameterPasswordProtected.cpp.o
> [ 90%] Building CXX object youbot_stack/youbot_driver/CMakeFiles/YouBotDriver.dir/youbot/JointTrajectoryController.cpp.o
> [ 92%] Building CXX object youbot_stack/youbot_driver/CMakeFiles/YouBotDriver.dir/base-kinematic/FourSwedishWheelOmniBaseKinematic.cpp.o
> [ 95%] Building CXX object youbot_stack/youbot_driver/CMakeFiles/YouBotDriver.dir/base-kinematic/FourSwedishWheelOmniBaseKinematicConfiguration.cpp.o
> [ 97%] Linking CXX shared library /home/osanda/catkin_ws/src/youbot_stack/youbot_driver/lib/libYouBotDriver.so
> [ 97%] Built target YouBotDriver
> Makefile:138: recipe for target 'all' failed
> make: *** [all] Error 2
> Invoking "make -j4 -l4" failed

**Comment by kpach** [comment]
Can you check whether you have the file "libsoem.so" in youbot_driver/lib?

**Comment by ossieG** [comment]
Yes

> osanda@MyPC101:~/catkin_ws$ find . -name libsoem.so
> ./src/youbot_stack/youbot_driver/lib/libsoem.so

**Comment by kpach** [comment]
There may be some problem with youbot_joint_control/lib/libYouBotDriver.so.
Can you try moving the file from youbot_driver/lib to replace the one in youbot_joint_control/lib?

If this doesn't work, I will try to build the package again tomorrow.

**Comment by ossieG** [comment]
I can only see one copy of within the whole catkin_ws directory. 

./src/youbot_stack/youbot_driver/lib/libsoem.so

Maybe the procedure the procedure in which i am doing is incorrect? 

I have cloned youbot _stack to youbot_stack folder within src.
Then opened the youbot_stack folder and update git. Then go back to catkin_ws and run cakin_make.

Is the folder structure that I have made correct?

**Comment by kpach** [comment]
I now remove the hardware stuff from the repository. You should be able to build the packages now.

**Comment by ossieG** [comment]
Worked! Thank you!
