### ISSUE TITLE
problem with roslaunch

### ISSUE THREAD

**Issue by wys2010** [surgical-vision/youbot_stack#3]
error occurs when I run roslaunch youbot_simulator youbot_sim.launch gui:=true
the error is shown below:

NODES
  /
    controller_spawner (controller_manager/spawner)
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    youbot_load_gazebo_model (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [3276]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to cd0d5a50-af9b-11e7-910a-b8e8561f639c
process[rosout-1]: started with pid [3289]
started core service [/rosout]
process[gazebo-2]: started with pid [3313]
process[gazebo_gui-3]: started with pid [3318]
process[youbot_load_gazebo_model-4]: started with pid [3323]
ERROR: cannot launch node of type [controller_manager/spawner]: controller_manager
ROS path [0]=/opt/ros/lunar/share/ros
ROS path [1]=/home/yinsong/catkin_ws/src
ROS path [2]=/opt/ros/lunar/share
process[robot_state_publisher-6]: started with pid [3324]
[ WARN] [1507846937.614380631]: The root link base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[ INFO] [1507846938.284079016]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1507846938.285945862]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
SpawnModel script started
[INFO] [1507846939.349167, 0.000000]: Loading model XML from ros parameter
[INFO] [1507846939.359681, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[ INFO] [1507846939.583579495, 0.024000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[INFO] [1507846939.668080, 0.089000]: Calling service /gazebo/spawn_urdf_model
[ INFO] [1507846939.707495890, 0.125000000]: Physics dynamic reconfigure ready.
Warning [parser_urdf.cc:1232] multiple inconsistent <self_collide> exists due to fixed joint reduction overwriting previous value [false] with [true].
[INFO] [1507846940.115120, 0.278000]: Spawn status: SpawnModel: Successfully spawned entity
[youbot_load_gazebo_model-4] process has finished cleanly
log file: /home/yinsong/.ros/log/cd0d5a50-af9b-11e7-910a-b8e8561f639c/youbot_load_gazebo_model-4*.log

**Comment by kpach** [comment]
Can you check whether you have controller_manager of devel lunar?
`apt list ros-lunar-controller-manager`

**Comment by wys2010** [comment]
I do have it.
~$ apt list ros-lunar-controller-manager
Listing... Done
ros-lunar-controller-manager/xenial 0.12.0-0xenial-20170815-140343-0800 amd64

**Comment by kpach** [comment]
Have you tried this?
https://answers.ros.org/question/247477/cant-locate-node-spawner-in-package-controller_manager/

**Comment by wys2010** [comment]
I am sorry that I might have made a mistake, I didn't have the controller_manager of devel lunar.
I reinstalled and it works.
and shows as:
$ apt list ros-lunar-controller-manager
Listing... Done
ros-lunar-controller-manager/xenial,now 0.12.0-0xenial-20170815-140343-0800 amd64 [installed,automatic]
